# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asker.TopicArea'),
            preserve_default=False,
        ),
    ]
